DROP TABLE IF EXISTS favoritos;
DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
    ID_CLIENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favoritos (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_CLIENTE INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    TITULO TEXT NOT NULL,
    IMAGEM TEXT,
    PRECO REAL,
    AVALIACAO REAL,
    CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLIENTE) REFERENCES clientes(ID_CLIENTE) ON DELETE CASCADE,
    UNIQUE(ID_CLIENTE, ID_PRODUTO)
);